insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (1, '29', '5', 'Spin', 'Pilates core workout', 'legs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (2, '37', '12', 'Barre', 'Bootcamp circuit training', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (3, '31', '19', 'Spin', 'Yoga fusion', 'legs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (4, '21', '40', 'Zumba', 'Zumba dance fitness', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (5, '38', '32', 'Bootcamp', 'Yoga fusion', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (6, '22', '23', 'Pilates', 'Zumba dance fitness', 'chest');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (7, '18', '24', 'Bootcamp', 'Pilates core workout', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (8, '8', '37', 'Zumba', 'Zumba dance fitness', 'legs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (9, '33', '8', 'Zumba', 'Bootcamp circuit training', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (10, '30', '13', 'Barre', 'Yoga fusion', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (11, '16', '18', 'Bootcamp', 'Zumba dance fitness', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (12, '35', '36', 'Yoga', 'Pilates core workout', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (13, '20', '33', 'Kickboxing', 'Bootcamp circuit training', 'chest');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (14, '4', '31', 'Spin', 'Yoga fusion', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (15, '36', '11', 'Spin', 'Pilates core workout', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (16, '27', '3', 'CrossFit', 'Zumba dance fitness', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (17, '3', '38', 'Zumba', 'Pilates core workout', 'back');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (18, '7', '34', 'Spin', 'Zumba dance fitness', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (19, '13', '4', 'Barre', 'Bootcamp circuit training', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (20, '17', '7', 'Pilates', 'Yoga fusion', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (21, '32', '25', 'Kickboxing', 'High-intensity interval training', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (22, '10', '39', 'Yoga', 'Zumba dance fitness', 'chest');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (23, '28', '30', 'CrossFit', 'Pilates core workout', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (24, '19', '21', 'Bootcamp', 'Zumba dance fitness', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (25, '24', '16', 'Yoga', 'Yoga fusion', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (26, '11', '14', 'Spin', 'Yoga fusion', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (27, '25', '27', 'Bootcamp', 'Pilates core workout', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (28, '39', '28', 'Bootcamp', 'Bootcamp circuit training', 'chest');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (29, '12', '17', 'CrossFit', 'Bootcamp circuit training', 'back');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (30, '9', '1', 'Yoga', 'Pilates core workout', 'abs');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (31, '34', '26', 'Bootcamp', 'Bootcamp circuit training', 'back');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (32, '15', '10', 'Yoga', 'High-intensity interval training', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (33, '14', '6', 'Barre', 'High-intensity interval training', 'back');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (34, '6', '15', 'Barre', 'Yoga fusion', 'back');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (35, '40', '35', 'Zumba', 'High-intensity interval training', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (36, '23', '22', 'Spin', 'Pilates core workout', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (37, '5', '29', 'Spin', 'Zumba dance fitness', 'back');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (38, '2', '20', 'Bootcamp', 'Yoga fusion', 'arms');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (39, '26', '9', 'Yoga', 'Yoga fusion', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (40, '1', '2', 'Kickboxing', 'Pilates core workout', 'shoulders');
insert into Fitness_Class (Class_ID, Gym_ID, Instructor_ID, Name, Description, Focus) values (41, '2', '15', 'Bootcamp', 'Pilates core workout', 'shoulders');
