insert into Gym (gym_id, name, address) values (1, 'FitZone', '67 Jackson Road');
insert into Gym (gym_id, name, address) values (2, 'Body Blast', '78 Moulton Plaza');
insert into Gym (gym_id, name, address) values (3, 'Peak Physique', '269 Fair Oaks Street');
insert into Gym (gym_id, name, address) values (4, 'Body Blast', '6 Basil Park');
insert into Gym (gym_id, name, address) values (5, 'Flex Fitness', '60927 Carpenter Plaza');
insert into Gym (gym_id, name, address) values (6, 'FitZone', '2824 Vahlen Terrace');
insert into Gym (gym_id, name, address) values (7, 'FitZone', '7522 Union Trail');
insert into Gym (gym_id, name, address) values (8, 'FitZone', '49225 Sage Road');
insert into Gym (gym_id, name, address) values (9, 'Iron Strong Gym', '1 Pankratz Crossing');
insert into Gym (gym_id, name, address) values (10, 'Muscle Haven', '24 Thompson Place');
insert into Gym (gym_id, name, address) values (11, 'FitZone', '9789 Hovde Junction');
insert into Gym (gym_id, name, address) values (12, 'Body Blast', '438 West Hill');
insert into Gym (gym_id, name, address) values (13, 'Gymfinity', '5037 Twin Pines Road');
insert into Gym (gym_id, name, address) values (14, 'Peak Physique', '29 Fairfield Crossing');
insert into Gym (gym_id, name, address) values (15, 'Elite Performance', '346 Forster Hill');
insert into Gym (gym_id, name, address) values (16, 'Peak Physique', '4 Melrose Parkway');
insert into Gym (gym_id, name, address) values (17, 'Peak Physique', '0 Golden Leaf Street');
insert into Gym (gym_id, name, address) values (18, 'Iron Strong Gym', '5696 Scoville Avenue');
insert into Gym (gym_id, name, address) values (19, 'Peak Physique', '74 Butterfield Junction');
insert into Gym (gym_id, name, address) values (20, 'Sweat City', '92371 Goodland Terrace');
insert into Gym (gym_id, name, address) values (21, 'Powerhouse Gym', '48970 Straubel Lane');
insert into Gym (gym_id, name, address) values (22, 'FitZone', '62 Service Pass');
insert into Gym (gym_id, name, address) values (23, 'Flex Fitness', '866 Washington Trail');
insert into Gym (gym_id, name, address) values (24, 'Elite Performance', '2110 West Terrace');
insert into Gym (gym_id, name, address) values (25, 'Peak Physique', '083 Warrior Alley');
insert into Gym (gym_id, name, address) values (26, 'Body Blast', '61 Mallory Avenue');
insert into Gym (gym_id, name, address) values (27, 'Elite Performance', '7989 Leroy Park');
insert into Gym (gym_id, name, address) values (28, 'Muscle Haven', '730 Mariners Cove Alley');
insert into Gym (gym_id, name, address) values (29, 'Sweat City', '1 Nelson Point');
insert into Gym (gym_id, name, address) values (30, 'Muscle Haven', '231 Sommers Place');
insert into Gym (gym_id, name, address) values (31, 'Iron Strong Gym', '986 Brown Terrace');
insert into Gym (gym_id, name, address) values (32, 'Iron Strong Gym', '230 Express Trail');
insert into Gym (gym_id, name, address) values (33, 'Gymfinity', '89 Summit Trail');
insert into Gym (gym_id, name, address) values (34, 'Muscle Haven', '460 Orin Avenue');
insert into Gym (gym_id, name, address) values (35, 'Sweat City', '54 Vernon Plaza');
insert into Gym (gym_id, name, address) values (36, 'Flex Fitness', '4 Arrowood Pass');
insert into Gym (gym_id, name, address) values (37, 'Sweat City', '4755 Texas Street');
insert into Gym (gym_id, name, address) values (38, 'Flex Fitness', '67668 Maryland Place');
insert into Gym (gym_id, name, address) values (39, 'Elite Performance', '826 Iowa Place');
insert into Gym (gym_id, name, address) values (40, 'FitZone', '730 Becker Drive');
insert into Gym (gym_id, name, address) values (41, 'Body Blast', '8832 Transport Terrace');
