insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (1, 'HIIT Circuit', 'CrossFit challenge', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (2, 'Pilates Fusion', 'Cardio-focused plan', 'shoulders');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (3, 'Yoga Flow', 'HIIT workout routine', 'core');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (4, 'Pilates Fusion', 'Strength training program', 'core');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (5, 'Strength Training', 'Yoga and meditation schedule', 'legs');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (6, 'Pilates Fusion', 'Strength training program', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (7, 'Strength Training', 'Cardio-focused plan', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (8, 'Cardio Blast', 'Strength training program', 'shoulders');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (9, 'Yoga Flow', 'Yoga and meditation schedule', 'chest');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (10, 'Yoga Flow', 'CrossFit challenge', 'legs');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (11, 'Strength Training', 'Yoga and meditation schedule', 'chest');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (12, 'Cardio Blast', 'CrossFit challenge', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (13, 'Strength Training', 'Cardio-focused plan', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (14, 'HIIT Circuit', 'Yoga and meditation schedule', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (15, 'Cardio Blast', 'Cardio-focused plan', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (16, 'Pilates Fusion', 'Cardio-focused plan', 'legs');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (17, 'Yoga Flow', 'Cardio-focused plan', 'core');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (18, 'Cardio Blast', 'HIIT workout routine', 'legs');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (19, 'Strength Training', 'Strength training program', 'shoulders');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (20, 'Yoga Flow', 'Strength training program', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (21, 'Pilates Fusion', 'HIIT workout routine', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (22, 'Pilates Fusion', 'CrossFit challenge', 'shoulders');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (23, 'Yoga Flow', 'HIIT workout routine', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (24, 'Strength Training', 'Cardio-focused plan', 'legs');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (25, 'Yoga Flow', 'CrossFit challenge', 'legs');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (26, 'Strength Training', 'CrossFit challenge', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (27, 'HIIT Circuit', 'Strength training program', 'chest');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (28, 'HIIT Circuit', 'Yoga and meditation schedule', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (29, 'Strength Training', 'Yoga and meditation schedule', 'chest');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (30, 'Cardio Blast', 'Cardio-focused plan', 'core');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (31, 'Cardio Blast', 'HIIT workout routine', 'core');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (32, 'Yoga Flow', 'Cardio-focused plan', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (33, 'HIIT Circuit', 'CrossFit challenge', 'shoulders');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (34, 'Strength Training', 'CrossFit challenge', 'core');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (35, 'Yoga Flow', 'Strength training program', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (36, 'HIIT Circuit', 'HIIT workout routine', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (37, 'Cardio Blast', 'CrossFit challenge', 'back');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (38, 'Strength Training', 'HIIT workout routine', 'arms');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (39, 'Cardio Blast', 'HIIT workout routine', 'chest');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (40, 'Pilates Fusion', 'Cardio-focused plan', 'shoulders');
insert into Workout_Plan (Plan_ID, Name, Description, Focus) values (41, 'HIIT Circuit', 'HIIT workout routine', 'chest');
