insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (1, '1', 'treadmill', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (2, '29', 'rowing machine', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (3, '13', 'elliptical machine', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (4, '31', 'rowing machine', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (5, '10', 'elliptical machine', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (6, '19', 'elliptical machine', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (7, '37', 'elliptical machine', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (8, '8', 'dumbbell', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (9, '11', 'exercise bike', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (10, '27', 'treadmill', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (11, '20', 'leg press machine', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (12, '5', 'exercise bike', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (13, '40', 'exercise bike', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (14, '30', 'exercise bike', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (15, '3', 'leg press machine', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (16, '14', 'rowing machine', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (17, '4', 'dumbbell', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (18, '34', 'dumbbell', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (19, '39', 'dumbbell', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (20, '15', 'leg press machine', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (21, '9', 'elliptical machine', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (22, '24', 'treadmill', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (23, '16', 'leg press machine', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (24, '12', 'leg press machine', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (25, '2', 'elliptical machine', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (26, '25', 'dumbbell', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (27, '18', 'rowing machine', 'hamstrings');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (28, '21', 'dumbbell', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (29, '33', 'leg press machine', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (30, '32', 'dumbbell', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (31, '35', 'treadmill', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (32, '6', 'elliptical machine', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (33, '26', 'leg press machine', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (34, '22', 'exercise bike', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (35, '36', 'treadmill', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (36, '7', 'exercise bike', 'calves');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (37, '38', 'treadmill', 'triceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (38, '23', 'leg press machine', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (39, '28', 'elliptical machine', 'quadriceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (40, '17', 'leg press machine', 'biceps');
insert into Equipment (Equipment_ID, Gym_ID, Name, Target_Muscle) values (41, '33', 'treadmill', 'quadriceps');
